apiVersion: v1
kind: Service
metadata:
  name: knodex-redis
  labels:
    app.kubernetes.io/name: knodex
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: knodex
    app.kubernetes.io/component: redis
