// Copyright 2026 Knodex Authors
// SPDX-License-Identifier: AGPL-3.0-only

// AUTO-GENERATED by web/scripts/build-tokens.mjs from tokens.json — DO NOT EDIT BY HAND.

/** Union of every design-token CSS custom-property name (with leading `--`). */
export type TokenName =
  | "--surface-bg"
  | "--surface-primary"
  | "--surface-elevated"
  | "--status-healthy"
  | "--status-warning"
  | "--status-warning-hsl"
  | "--status-error"
  | "--status-info"
  | "--status-inactive"
  | "--brand-primary"
  | "--brand-hover"
  | "--text-primary"
  | "--text-secondary"
  | "--text-muted"
  | "--text-disabled"
  | "--text-size-2xl"
  | "--text-size-xl"
  | "--text-size-lg"
  | "--text-size-base"
  | "--text-size-sm"
  | "--text-size-xs"
  | "--space-1"
  | "--space-2"
  | "--space-3"
  | "--space-4"
  | "--space-5"
  | "--space-6"
  | "--space-8"
  | "--space-10"
  | "--space-12"
  | "--radius-token-sm"
  | "--radius-token-md"
  | "--radius-token-lg"
  | "--radius-token-full"
  | "--border-subtle"
  | "--border-default"
  | "--border-hover"
  | "--border-active"
  | "--shadow-token-sm"
  | "--shadow-token-md"
  | "--shadow-token-lg"
  | "--shadow-card-hover"
  | "--gradient-brand"
  | "--gradient-brand-subtle"
  | "--teal-50"
  | "--teal-100"
  | "--teal-400"
  | "--teal-500"
  | "--teal-600"
  | "--teal"
  | "--teal-dark"
  | "--teal-light"
  | "--violet-50"
  | "--violet-100"
  | "--violet-400"
  | "--violet-500"
  | "--violet-600"
  | "--violet"
  | "--violet-light"
  | "--blue-50"
  | "--blue-100"
  | "--blue-400"
  | "--blue-500"
  | "--blue-600"
  | "--blue"
  | "--rose-50"
  | "--rose-100"
  | "--rose-400"
  | "--rose-500"
  | "--rose-600"
  | "--amber-50"
  | "--amber-100"
  | "--amber-400"
  | "--amber-500"
  | "--amber-600"
  | "--gray-50"
  | "--gray-100"
  | "--gray-200"
  | "--gray-300"
  | "--gray-400"
  | "--gray-500"
  | "--gray-600"
  | "--gray-700"
  | "--gray-800"
  | "--gray-900"
  | "--avatar-tone-1-bg-hsl"
  | "--avatar-tone-1-fg"
  | "--avatar-tone-2-bg-hsl"
  | "--avatar-tone-2-fg"
  | "--avatar-tone-3-bg-hsl"
  | "--avatar-tone-3-fg"
  | "--avatar-tone-4-bg-hsl"
  | "--avatar-tone-4-fg"
  | "--avatar-tone-5-bg-hsl"
  | "--avatar-tone-5-fg"
  | "--avatar-tone-6-bg-hsl"
  | "--avatar-tone-6-fg"
  | "--avatar-tone-7-bg-hsl"
  | "--avatar-tone-7-fg";

/** Map of every design token to its string value. */
export type TokenMap = { [K in TokenName]: string };

/** Tailwind preset shape exported by `@knodex/design-tokens`. */
export interface DesignTokensPreset {
  theme: {
    extend: {
      colors: Record<string, string>;
      fontSize: Record<string, string>;
      spacing: Record<string, string>;
      borderRadius: Record<string, string>;
      boxShadow: Record<string, string>;
      backgroundImage: Record<string, string>;
    };
  };
  tokens: TokenMap;
  tokenNames: readonly TokenName[];
}

declare const preset: DesignTokensPreset;
export default preset;
