package rbac

import (
	"embed"
	"fmt"
	"strings"
	"sync"

	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/model"

	"github.com/knodex/knodex/server/internal/util/sanitize"
)

// Security constants for input validation
const (
	MaxResourceNameLength = 256
	MaxSubjectIDLength    = 256
	MaxProjectNameLength  = 128
	MaxRoleNameLength     = 64
	MaxWildcards          = 10
	MaxPatternLength      = 500
)

//go:embed casbin_model.conf
var casbinModelFS embed.FS

// CasbinEnforcer wraps Casbin enforcer with helper methods for RBAC operations
type CasbinEnforcer struct {
	enforcer *casbin.Enforcer
	mu       sync.RWMutex
}

// NewCasbinEnforcer creates a new Casbin enforcer with built-in policies
func NewCasbinEnforcer() (*CasbinEnforcer, error) {
	// Load model from embedded file
	modelContent, err := casbinModelFS.ReadFile("casbin_model.conf")
	if err != nil {
		return nil, fmt.Errorf("failed to read casbin model: %w", err)
	}

	// Parse model
	m, err := model.NewModelFromString(string(modelContent))
	if err != nil {
		return nil, fmt.Errorf("failed to parse casbin model: %w", err)
	}

	// Create enforcer with in-memory adapter (no adapter = in-memory)
	enforcer, err := casbin.NewEnforcer(m)
	if err != nil {
		return nil, fmt.Errorf("failed to create casbin enforcer: %w", err)
	}

	// Enable auto-save (policies persist to adapter automatically)
	enforcer.EnableAutoSave(false)

	// Load built-in policies (no lock needed during initialization - single-threaded)
	if err := loadBuiltinPoliciesLocked(enforcer); err != nil {
		return nil, fmt.Errorf("failed to load built-in policies: %w", err)
	}

	return &CasbinEnforcer{enforcer: enforcer}, nil
}

// NewCasbinEnforcerFromString creates an enforcer from a model string (for testing)
func NewCasbinEnforcerFromString(modelText string) (*CasbinEnforcer, error) {
	m, err := model.NewModelFromString(modelText)
	if err != nil {
		return nil, fmt.Errorf("failed to parse casbin model: %w", err)
	}

	enforcer, err := casbin.NewEnforcer(m)
	if err != nil {
		return nil, fmt.Errorf("failed to create casbin enforcer: %w", err)
	}

	enforcer.EnableAutoSave(false)

	// Load built-in policies (no lock needed during initialization - single-threaded)
	if err := loadBuiltinPoliciesLocked(enforcer); err != nil {
		return nil, fmt.Errorf("failed to load built-in policies: %w", err)
	}

	return &CasbinEnforcer{enforcer: enforcer}, nil
}

// loadBuiltinPoliciesLocked adds global roles and default policies
// IMPORTANT: Caller MUST hold the mutex lock before calling this method
//
// This function is the SINGLE SOURCE OF TRUTH for all built-in role permissions.
// All role-based permissions are consolidated here. See docs/rbac-permissions.md for the
// complete permission reference.
//
// Server-Level Role Model:
// - role:serveradmin - Full access to everything including server-level operations (SSO, audit, license)
//
// Project-scoped roles (admin, developer, readonly) are defined in Project CRD spec.roles
// and auto-generated by getBuiltInProjectPolicies(). No global readonly role exists.
//
// Custom roles (platform-admin, developer, etc.) should be defined in Project CRD with explicit policies.
func loadBuiltinPoliciesLocked(e *casbin.Enforcer) error {
	// Built-in policies for server-level role model
	// Format: {subject, object, action, effect}
	policies := [][]string{
		// ========================================
		// SERVERADMIN - Full access to everything including server-level operations
		// ========================================
		// Wildcard policy for admin bypass checks (e.g., CanAccess(userID, "*", "*"))
		// This enables handlers and middleware to detect admin status via permission checks
		{"role:serveradmin", "*", "*", "allow"},
		// Explicit resource policies (for clarity and documentation)
		{"role:serveradmin", "projects/*", "*", "allow"},
		{"role:serveradmin", "rgds/*", "*", "allow"},
		{"role:serveradmin", "instances/*", "*", "allow"},
		{"role:serveradmin", "users/*", "*", "allow"},
		{"role:serveradmin", "applications/*", "*", "allow"},
		{"role:serveradmin", "repositories/*", "*", "allow"},
		{"role:serveradmin", "namespaces/*", "*", "allow"},
		// Settings access for serveradmin (SSO, audit, license)
		{"role:serveradmin", "settings/*", "*", "allow"},
		// Compliance access for serveradmin (Enterprise: OPA Gatekeeper compliance view)
		{"role:serveradmin", "compliance/*", "*", "allow"},
	}

	// Add policies
	for _, policy := range policies {
		if _, err := e.AddPolicy(policy); err != nil {
			return fmt.Errorf("failed to add policy %v: %w", policy, err)
		}
	}

	return nil
}

// Enforce checks if a subject can perform an action on an object
func (ce *CasbinEnforcer) Enforce(sub, obj, act string) (bool, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.Enforce(sub, obj, act)
}

// AddPolicy adds a single policy rule
func (ce *CasbinEnforcer) AddPolicy(sub, obj, act, eft string) (bool, error) {
	ce.mu.Lock()
	defer ce.mu.Unlock()
	return ce.enforcer.AddPolicy(sub, obj, act, eft)
}

// RemovePolicy removes a single policy rule
func (ce *CasbinEnforcer) RemovePolicy(sub, obj, act, eft string) (bool, error) {
	ce.mu.Lock()
	defer ce.mu.Unlock()
	return ce.enforcer.RemovePolicy(sub, obj, act, eft)
}

// AddUserRole assigns a role to a user
func (ce *CasbinEnforcer) AddUserRole(user, role string) (bool, error) {
	ce.mu.Lock()
	defer ce.mu.Unlock()
	return ce.enforcer.AddGroupingPolicy(user, role)
}

// RemoveUserRole removes a role from a user
func (ce *CasbinEnforcer) RemoveUserRole(user, role string) (bool, error) {
	ce.mu.Lock()
	defer ce.mu.Unlock()
	return ce.enforcer.RemoveGroupingPolicy(user, role)
}

// GetRolesForUser returns all roles for a user
func (ce *CasbinEnforcer) GetRolesForUser(user string) ([]string, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.GetRolesForUser(user)
}

// GetUsersForRole returns all users that have a specific role
func (ce *CasbinEnforcer) GetUsersForRole(role string) ([]string, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.GetUsersForRole(role)
}

// GetPoliciesForRole returns all policies for a role
func (ce *CasbinEnforcer) GetPoliciesForRole(role string) ([][]string, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.GetFilteredPolicy(0, role)
}

// GetAllPolicies returns all policies
func (ce *CasbinEnforcer) GetAllPolicies() ([][]string, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.GetPolicy()
}

// GetAllRoles returns all defined roles
func (ce *CasbinEnforcer) GetAllRoles() ([]string, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.GetAllRoles()
}

// HasPolicy checks if a policy exists
func (ce *CasbinEnforcer) HasPolicy(sub, obj, act, eft string) (bool, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.HasPolicy(sub, obj, act, eft)
}

// HasUserRole checks if a user has a specific role
func (ce *CasbinEnforcer) HasUserRole(user, role string) (bool, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.HasGroupingPolicy(user, role)
}

// ClearPolicies removes all policies (except built-in)
func (ce *CasbinEnforcer) ClearPolicies() error {
	ce.mu.Lock()
	defer ce.mu.Unlock()

	// Clear all policies
	ce.enforcer.ClearPolicy()

	// Reload built-in policies while holding the lock (fixes race condition)
	return loadBuiltinPoliciesLocked(ce.enforcer)
}

// AddRoleInheritance adds role-to-role inheritance (g2)
func (ce *CasbinEnforcer) AddRoleInheritance(childRole, parentRole string) (bool, error) {
	ce.mu.Lock()
	defer ce.mu.Unlock()
	return ce.enforcer.AddNamedGroupingPolicy("g2", childRole, parentRole)
}

// RemoveRoleInheritance removes role-to-role inheritance (g2)
func (ce *CasbinEnforcer) RemoveRoleInheritance(childRole, parentRole string) (bool, error) {
	ce.mu.Lock()
	defer ce.mu.Unlock()
	return ce.enforcer.RemoveNamedGroupingPolicy("g2", childRole, parentRole)
}

// GetImplicitRolesForUser returns all roles a user has (including inherited roles)
func (ce *CasbinEnforcer) GetImplicitRolesForUser(user string) ([]string, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.GetImplicitRolesForUser(user)
}

// GetImplicitPermissionsForUser returns all permissions for a user (including inherited)
func (ce *CasbinEnforcer) GetImplicitPermissionsForUser(user string) ([][]string, error) {
	ce.mu.RLock()
	defer ce.mu.RUnlock()
	return ce.enforcer.GetImplicitPermissionsForUser(user)
}

// Built-in Casbin role constants
// Note: These are prefixed with "Casbin" to avoid conflict with Role type in permission_service.go
// All role permissions are defined in loadBuiltinPoliciesLocked()
//
// Server-Level Role Model:
// - role:serveradmin - Full access to everything including server-level operations (SSO, audit, license)
//
// Project-scoped roles (admin, developer, readonly) are defined in Project CRD spec.roles.
// No global readonly role exists — readonly access is project-scoped only.
//
// Custom roles (platform-admin, developer, etc.) should be defined in Project CRD with explicit policies.
const (
	// CasbinRoleServerAdmin grants full access to all resources including server-level operations
	CasbinRoleServerAdmin = "role:serveradmin"
)

// Resource type prefixes for object formatting
// Added settings resource for Settings sidebar RBAC
// Added compliance resource for OPA Gatekeeper compliance view (Enterprise only)
const (
	ResourceProjects     = "projects"
	ResourceRGDs         = "rgds"
	ResourceInstances    = "instances"
	ResourceUsers        = "users"
	ResourceApplications = "applications"
	ResourceRepositories = "repositories"
	ResourceSettings     = "settings"
	ResourceCompliance   = "compliance"
)

// Action constants
const (
	ActionGet    = "get"
	ActionList   = "list"
	ActionCreate = "create"
	ActionUpdate = "update"
	ActionDelete = "delete"
)

// Effect constants
const (
	EffectAllow = "allow"
	EffectDeny  = "deny"
)

// --- Security Validation Functions ---

// ValidateSubjectIdentifier validates identifiers for users, groups, and roles
// to prevent injection attacks via subject manipulation
func ValidateSubjectIdentifier(id string) error {
	if id == "" {
		return fmt.Errorf("identifier cannot be empty")
	}

	// Check length limit
	if len(id) > MaxSubjectIDLength {
		return fmt.Errorf("identifier exceeds maximum length of %d", MaxSubjectIDLength)
	}

	// Disallow control characters, colons (prefix separator), and spaces
	if strings.ContainsAny(id, ":\n\r\t ") {
		return fmt.Errorf("identifier contains invalid characters (no colons, newlines, or spaces allowed)")
	}

	// Ensure it doesn't start with reserved prefixes (case-insensitive)
	lower := strings.ToLower(id)
	forbidden := []string{"role:", "user:", "group:", "proj:"}
	for _, prefix := range forbidden {
		if strings.HasPrefix(lower, prefix) {
			return fmt.Errorf("identifier cannot start with reserved prefix: %s", prefix)
		}
	}

	return nil
}

// ValidateGlobPattern validates glob patterns to prevent ReDoS attacks
func ValidateGlobPattern(pattern string) error {
	if pattern == "" {
		return nil // Empty patterns are allowed
	}

	// Check pattern length
	if len(pattern) > MaxPatternLength {
		return fmt.Errorf("pattern too long (max %d chars): %d", MaxPatternLength, len(pattern))
	}

	// Count wildcards
	wildcardCount := strings.Count(pattern, "*") + strings.Count(pattern, "?")
	if wildcardCount > MaxWildcards {
		return fmt.Errorf("pattern has too many wildcards (max %d): %d", MaxWildcards, wildcardCount)
	}

	// Disallow nested or consecutive wildcards like ** or ??
	if strings.Contains(pattern, "**") || strings.Contains(pattern, "??") {
		return fmt.Errorf("nested or consecutive wildcards not allowed")
	}

	return nil
}

// ValidateEffect validates the policy effect
func ValidateEffect(eft string) error {
	if eft != EffectAllow && eft != EffectDeny {
		return fmt.Errorf("invalid effect: must be '%s' or '%s', got '%s'", EffectAllow, EffectDeny, eft)
	}
	return nil
}

// --- Secure Formatting Functions ---

// FormatObject creates a properly formatted object string for policy matching
// Returns an error if the resource name contains invalid characters
func FormatObject(resourceType, resourceName string) (string, error) {
	if resourceName == "" || resourceName == "*" {
		return resourceType + "/*", nil
	}

	// Validate resource name length
	if len(resourceName) > MaxResourceNameLength {
		return "", fmt.Errorf("resource name exceeds maximum length of %d", MaxResourceNameLength)
	}

	// Sanitize resource name to prevent glob injection
	sanitized := sanitize.GlobCharacters(resourceName)
	return resourceType + "/" + sanitized, nil
}

// FormatObjectUnsafe creates an object string without sanitization
// WARNING: Only use this for trusted/validated input (e.g., built-in policies)
func FormatObjectUnsafe(resourceType, resourceName string) string {
	if resourceName == "" || resourceName == "*" {
		return resourceType + "/*"
	}
	return resourceType + "/" + resourceName
}

// FormatProjectRole creates a project-specific role name
// Returns an error if project or role name contains invalid characters
func FormatProjectRole(projectName, roleName string) (string, error) {
	if len(projectName) > MaxProjectNameLength {
		return "", fmt.Errorf("project name exceeds maximum length of %d", MaxProjectNameLength)
	}
	if len(roleName) > MaxRoleNameLength {
		return "", fmt.Errorf("role name exceeds maximum length of %d", MaxRoleNameLength)
	}

	if err := ValidateSubjectIdentifier(projectName); err != nil {
		return "", fmt.Errorf("invalid project name: %w", err)
	}
	if err := ValidateSubjectIdentifier(roleName); err != nil {
		return "", fmt.Errorf("invalid role name: %w", err)
	}

	return fmt.Sprintf("proj:%s:%s", projectName, roleName), nil
}

// FormatUserSubject creates a user subject string
// Returns an error if userID contains invalid characters
func FormatUserSubject(userID string) (string, error) {
	if err := ValidateSubjectIdentifier(userID); err != nil {
		return "", fmt.Errorf("invalid user ID: %w", err)
	}
	return "user:" + userID, nil
}

// FormatGroupSubject creates a group subject string
// Returns an error if groupName contains invalid characters
func FormatGroupSubject(groupName string) (string, error) {
	if err := ValidateSubjectIdentifier(groupName); err != nil {
		return "", fmt.Errorf("invalid group name: %w", err)
	}
	return "group:" + groupName, nil
}
