apiVersion: v1
kind: ConfigMap
metadata:
  name: knodex-sso-providers
data:
  providers.json: |
    [
      {
        "name": "azuread",
        "issuerURL": "https://login.microsoftonline.com/1c012acb-06ba-4a2c-8cd0-eda196f27fe7/v2.0",
        "redirectURL": "http://localhost:8080/api/v1/auth/oidc/callback",
        "scopes": ["openid", "email", "profile"]
      }
    ]
---
apiVersion: v1
kind: Secret
metadata:
  name: knodex-sso-secrets
type: Opaque
stringData:
  azuread.client-id: "3ed66e56-a325-4cbd-a6a4-f4cd9b07dad0"
  azuread.client-secret: "your-azure-ad-client-secret-here"
