# CI test values: existingSecret mode for both license and SSO
# Validates chart-managed Secrets are suppressed and deployment references user-provided secret names.

enterprise:
  enabled: true
  license:
    existingSecret: "my-license-secret"

server:
  auth:
    oidc:
      enabled: true
      existingSecret: "my-sso-secret"
      providers:
        - name: azure-ad
          issuerURL: https://login.microsoftonline.com/test-tenant/v2.0
          clientID: test-client
