// Copyright 2026 Knodex Authors
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * build-tokens.mjs — deterministic builder for the @knodex/design-tokens package.
 *
 * Reads the single source of truth (`web/src/design-tokens/tokens.json`) and emits
 * the three generated package artifacts described by architecture D-8:
 *   - css/tokens.css     CSS custom-properties build (consumed by knodex-ee)
 *   - tailwind-preset.js  Tailwind preset object (consumed by knodex-cloud-v2 / JS configs)
 *   - index.d.ts          TypeScript types for the tokens + preset
 *
 * The build is reproducible: ordering is taken verbatim from tokens.json (group
 * array order, then token insertion order), so running it twice yields
 * byte-identical output. The pure builder functions are exported so tests can
 * assert determinism, value-parity, and that the committed artifacts are in sync.
 *
 * Run:  node scripts/build-tokens.mjs   (from web/)  — or `npm run build:tokens`
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const PACKAGE_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'design-tokens',
);

const CSS_HEADER = '/* SPDX-License-Identifier: AGPL-3.0-only */';
const JS_HEADER = '// Copyright 2026 Knodex Authors\n// SPDX-License-Identifier: AGPL-3.0-only';
const GENERATED_NOTICE = 'AUTO-GENERATED by web/scripts/build-tokens.mjs from tokens.json — DO NOT EDIT BY HAND.';

// Maps a tokens.json group `category` to a Tailwind theme.extend key.
const CATEGORY_TO_THEME_KEY = {
  color: 'colors',
  fontSize: 'fontSize',
  spacing: 'spacing',
  borderRadius: 'borderRadius',
  boxShadow: 'boxShadow',
  gradient: 'backgroundImage',
};

/** Load and parse tokens.json from the package directory. */
export function loadTokens(packageDir = PACKAGE_DIR) {
  return JSON.parse(readFileSync(path.join(packageDir, 'tokens.json'), 'utf8'));
}

/** Flatten groups to an ordered array of [cssVarName, value] pairs (no `--` stripped). */
export function flattenTokens(tokens) {
  const pairs = [];
  for (const group of tokens.groups) {
    for (const [name, value] of Object.entries(group.tokens)) {
      pairs.push([`--${name}`, value]);
    }
  }
  return pairs;
}

/** Build css/tokens.css — reproduces the canonical custom-property values verbatim. */
export function buildCss(tokens) {
  const lines = [
    CSS_HEADER,
    '',
    `/* ${GENERATED_NOTICE} */`,
    '/*',
    ' * Knodex Design Tokens — shared primitives (the cross-repo source of truth).',
    ' * Consumed by knodex-ee via `@import "@knodex/design-tokens/css/tokens.css"`.',
    ' */',
    '',
    ':root {',
  ];
  tokens.groups.forEach((group, idx) => {
    if (idx > 0) lines.push('');
    lines.push(`  /* ── ${group.label} ── */`);
    for (const [name, value] of Object.entries(group.tokens)) {
      lines.push(`  --${name}: ${value};`);
    }
  });
  lines.push('}', '');
  return lines.join('\n');
}

/** Serialize a flat string→string record as a stable 2-space-indented JS object body. */
function serializeRecord(record, indent) {
  const pad = ' '.repeat(indent);
  return Object.entries(record)
    .map(([key, value]) => `${pad}${JSON.stringify(key)}: ${JSON.stringify(value)},`)
    .join('\n');
}

/** Build tailwind-preset.js — a CommonJS Tailwind preset plus raw token maps. */
export function buildPreset(tokens) {
  /** @type {Record<string, Record<string,string>>} */
  const themeBuckets = {};
  for (const group of tokens.groups) {
    const themeKey = CATEGORY_TO_THEME_KEY[group.category];
    if (!themeKey) {
      throw new Error(`Unknown token category "${group.category}" in group "${group.id}"`);
    }
    themeBuckets[themeKey] ??= {};
    Object.assign(themeBuckets[themeKey], group.tokens);
  }

  const tokenMap = Object.fromEntries(flattenTokens(tokens));
  const tokenNames = Object.keys(tokenMap);

  const extendBody = Object.entries(themeBuckets)
    .map(([themeKey, record]) => `      ${themeKey}: {\n${serializeRecord(record, 8)}\n      },`)
    .join('\n');

  return `${JS_HEADER}

/* ${GENERATED_NOTICE} */

/**
 * Tailwind preset exposing the shared Knodex design primitives.
 * knodex-ee consumes the CSS build (css/tokens.css); this preset is provided
 * for JS-config Tailwind consumers (e.g. knodex-cloud-v2's Next.js layer):
 *   // tailwind.config.js
 *   module.exports = { presets: [require('@knodex/design-tokens')] };
 */
const preset = {
  theme: {
    extend: {
${extendBody}
    },
  },
};

/** Flat map of every CSS custom-property name (with leading \`--\`) to its value. */
preset.tokens = {
${serializeRecord(tokenMap, 2)}
};

/** Ordered list of every CSS custom-property name. */
preset.tokenNames = ${JSON.stringify(tokenNames, null, 2)};

module.exports = preset;
`;
}

/** Build index.d.ts — TypeScript types for the preset and token names. */
export function buildDts(tokens) {
  const tokenNames = flattenTokens(tokens).map(([name]) => name);
  const union = tokenNames.map((name) => `  | ${JSON.stringify(name)}`).join('\n');
  return `${JS_HEADER}

// ${GENERATED_NOTICE}

/** Union of every design-token CSS custom-property name (with leading \`--\`). */
export type TokenName =
${union};

/** Map of every design token to its string value. */
export type TokenMap = { [K in TokenName]: string };

/** Tailwind preset shape exported by \`@knodex/design-tokens\`. */
export interface DesignTokensPreset {
  theme: {
    extend: {
      colors: Record<string, string>;
      fontSize: Record<string, string>;
      spacing: Record<string, string>;
      borderRadius: Record<string, string>;
      boxShadow: Record<string, string>;
      backgroundImage: Record<string, string>;
    };
  };
  tokens: TokenMap;
  tokenNames: readonly TokenName[];
}

declare const preset: DesignTokensPreset;
export default preset;
`;
}

/** Build all artifacts as a name→contents map (pure; no filesystem writes). */
export function buildArtifacts(tokens) {
  return {
    'css/tokens.css': buildCss(tokens),
    'tailwind-preset.js': buildPreset(tokens),
    'index.d.ts': buildDts(tokens),
  };
}

/** Write all artifacts to disk under the package directory. */
export function writeArtifacts(packageDir = PACKAGE_DIR) {
  const tokens = loadTokens(packageDir);
  const artifacts = buildArtifacts(tokens);
  mkdirSync(path.join(packageDir, 'css'), { recursive: true });
  for (const [relPath, contents] of Object.entries(artifacts)) {
    writeFileSync(path.join(packageDir, relPath), contents);
  }
  return Object.keys(artifacts);
}

// Run as a script (not when imported by tests).
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const written = writeArtifacts();
  console.log(`build:tokens — wrote ${written.length} artifacts: ${written.join(', ')}`);
}
