{{- if or (gt (int .Values.server.replicaCount) 1) .Values.server.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "knodex.fullname" . }}-server
  labels:
    {{- include "knodex.server.labels" . | nindent 4 }}
spec:
  {{- if and (not (kindIs "invalid" .Values.server.pdb.maxUnavailable)) .Values.server.pdb.minAvailable }}
  {{- fail "server.pdb.maxUnavailable and server.pdb.minAvailable are mutually exclusive. To use maxUnavailable, set server.pdb.minAvailable to null" }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.server.pdb.maxUnavailable) }}
  maxUnavailable: {{ .Values.server.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.server.pdb.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "knodex.server.selectorLabels" . | nindent 6 }}
{{- end }}
