{{- if not .Values.server.auth.oidc.existingSecret }}
{{- $hasInlineSecrets := false }}
{{- range $provider := .Values.server.auth.oidc.providers }}
  {{- if $provider.clientSecret }}
    {{- $hasInlineSecrets = true }}
  {{- end }}
{{- end }}
{{- if and .Values.server.auth.oidc.enabled .Values.server.auth.oidc.providers $hasInlineSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knodex.ssoSecretName" . }}
  labels:
    {{- include "knodex.labels" . | nindent 4 }}
    app.kubernetes.io/component: sso
    knodex.io/config-type: sso
type: Opaque
stringData:
  {{- range $provider := .Values.server.auth.oidc.providers }}
  {{- if $provider.clientID }}
  {{ $provider.name }}.client-id: {{ $provider.clientID | quote }}
  {{- end }}
  {{- if $provider.clientSecret }}
  {{ $provider.name }}.client-secret: {{ $provider.clientSecret | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
