apiVersion: kro.run/v1alpha1
kind: WebApp
metadata:
  name: my-webapp-fullstack
  namespace: default
spec:
  name: fullstack-app
  database:
    enabled: true
    name: fullstack-db
  cache:
    enabled: true
    maxMemory: 512mb
