package deployment

import (
	"strings"
	"testing"
	"time"
)

func TestNewGenerator(t *testing.T) {
	g := NewGenerator()
	if g == nil {
		t.Fatal("NewGenerator() returned nil")
	}
	if !g.includeMetadata {
		t.Error("NewGenerator() includeMetadata should default to true")
	}
}

func TestGenerator_SetIncludeMetadata(t *testing.T) {
	g := NewGenerator()

	g.SetIncludeMetadata(false)
	if g.includeMetadata {
		t.Error("SetIncludeMetadata(false) should set includeMetadata to false")
	}

	g.SetIncludeMetadata(true)
	if !g.includeMetadata {
		t.Error("SetIncludeMetadata(true) should set includeMetadata to true")
	}
}

func TestGenerator_GenerateManifest(t *testing.T) {
	g := NewGenerator()
	now := time.Now()

	t.Run("nil request", func(t *testing.T) {
		_, err := g.GenerateManifest(nil)
		if err == nil {
			t.Error("expected error for nil request")
		}
		if !strings.Contains(err.Error(), "cannot be nil") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("empty name", func(t *testing.T) {
		req := &DeployRequest{
			Name:      "",
			Namespace: "default",
		}
		_, err := g.GenerateManifest(req)
		if err == nil {
			t.Error("expected error for empty name")
		}
		if !strings.Contains(err.Error(), "instance name is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("empty namespace", func(t *testing.T) {
		req := &DeployRequest{
			Name:      "test",
			Namespace: "",
		}
		_, err := g.GenerateManifest(req)
		if err == nil {
			t.Error("expected error for empty namespace")
		}
		if !strings.Contains(err.Error(), "instance namespace is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("empty api version", func(t *testing.T) {
		req := &DeployRequest{
			Name:       "test",
			Namespace:  "default",
			APIVersion: "",
			Kind:       "MyResource",
		}
		_, err := g.GenerateManifest(req)
		if err == nil {
			t.Error("expected error for empty api version")
		}
		if !strings.Contains(err.Error(), "api version is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("empty kind", func(t *testing.T) {
		req := &DeployRequest{
			Name:       "test",
			Namespace:  "default",
			APIVersion: "example.com/v1",
			Kind:       "",
		}
		_, err := g.GenerateManifest(req)
		if err == nil {
			t.Error("expected error for empty kind")
		}
		if !strings.Contains(err.Error(), "kind is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("valid request", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-123",
			Name:           "my-app",
			Namespace:      "production",
			APIVersion:     "kro.run/v1alpha1",
			Kind:           "Application",
			RGDName:        "application-stack",
			RGDNamespace:   "kro-system",
			DeploymentMode: ModeGitOps,
			ProjectID:      "proj-456",
			CreatedBy:      "user@example.com",
			CreatedAt:      now,
			Spec: map[string]interface{}{
				"replicas": 3,
				"image":    "nginx:latest",
			},
		}

		manifest, err := g.GenerateManifest(req)
		if err != nil {
			t.Fatalf("GenerateManifest() error: %v", err)
		}

		// Check header
		if !strings.Contains(manifest, "# Generated by Knodex") {
			t.Error("manifest should contain header comment")
		}
		if !strings.Contains(manifest, "Instance: production/my-app") {
			t.Error("manifest should contain instance info in header")
		}

		// Check basic structure
		if !strings.Contains(manifest, "apiVersion: kro.run/v1alpha1") {
			t.Error("manifest should contain apiVersion")
		}
		if !strings.Contains(manifest, "kind: Application") {
			t.Error("manifest should contain kind")
		}
		if !strings.Contains(manifest, "name: my-app") {
			t.Error("manifest should contain name")
		}
		if !strings.Contains(manifest, "namespace: production") {
			t.Error("manifest should contain namespace")
		}

		// Check labels
		if !strings.Contains(manifest, "app.kubernetes.io/name: my-app") {
			t.Error("manifest should contain app.kubernetes.io/name label")
		}
		// Note: KRO automatically sets kro.run/resource-graph-definition-name label
		// Note: app.kubernetes.io/managed-by is set by KRO or GitOps tool (ArgoCD/Flux)
		if !strings.Contains(manifest, "knodex.io/deployment-mode: gitops") {
			t.Error("manifest should contain deployment-mode label")
		}
		if !strings.Contains(manifest, "knodex.io/project: proj-456") {
			t.Error("manifest should contain project label")
		}

		// Check annotations - all dashboard-specific metadata uses knodex.io prefix
		if !strings.Contains(manifest, "knodex.io/instance-id: inst-123") {
			t.Error("manifest should contain instance-id annotation")
		}
		if !strings.Contains(manifest, "knodex.io/created-by: user@example.com") {
			t.Error("manifest should contain created-by annotation")
		}
		if !strings.Contains(manifest, "knodex.io/project-id: proj-456") {
			t.Error("manifest should contain project-id annotation")
		}

		// Check spec
		if !strings.Contains(manifest, "replicas: 3") {
			t.Error("manifest should contain spec replicas")
		}
		if !strings.Contains(manifest, "image: nginx:latest") {
			t.Error("manifest should contain spec image")
		}
	})

	t.Run("request without project", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-789",
			Name:           "simple-app",
			Namespace:      "default",
			APIVersion:     "kro.run/v1alpha1",
			Kind:           "Application",
			RGDName:        "simple",
			RGDNamespace:   "kro-system",
			DeploymentMode: ModeDirect,
			CreatedBy:      "admin",
			CreatedAt:      now,
			Spec:           map[string]interface{}{},
		}

		manifest, err := g.GenerateManifest(req)
		if err != nil {
			t.Fatalf("GenerateManifest() error: %v", err)
		}

		// Should not contain project fields
		if strings.Contains(manifest, "knodex.io/project:") {
			t.Error("manifest should not contain project label when not set")
		}
		if strings.Contains(manifest, "knodex.io/project-id:") {
			t.Error("manifest should not contain project-id annotation when not set")
		}
	})
}

func TestGenerator_GenerateMetadata(t *testing.T) {
	g := NewGenerator()
	now := time.Now()

	t.Run("nil request", func(t *testing.T) {
		_, err := g.GenerateMetadata(nil, "sha123")
		if err == nil {
			t.Error("expected error for nil request")
		}
	})

	t.Run("valid request", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-123",
			Name:           "my-app",
			Namespace:      "production",
			RGDName:        "application-stack",
			RGDNamespace:   "kro-system",
			ProjectID:      "proj-456",
			DeploymentMode: ModeGitOps,
			CreatedBy:      "user@example.com",
			CreatedAt:      now,
			Repository: &RepositoryConfig{
				ID: "repo-789",
			},
		}

		metadata, err := g.GenerateMetadata(req, "abc123def456")
		if err != nil {
			t.Fatalf("GenerateMetadata() error: %v", err)
		}

		// Check header
		if !strings.Contains(metadata, "# Knodex Instance Metadata") {
			t.Error("metadata should contain header comment")
		}

		// Check fields
		if !strings.Contains(metadata, "instanceId: inst-123") {
			t.Error("metadata should contain instanceId")
		}
		if !strings.Contains(metadata, "name: my-app") {
			t.Error("metadata should contain name")
		}
		if !strings.Contains(metadata, "namespace: production") {
			t.Error("metadata should contain namespace")
		}
		if !strings.Contains(metadata, "rgdName: application-stack") {
			t.Error("metadata should contain rgdName")
		}
		if !strings.Contains(metadata, "projectId: proj-456") {
			t.Error("metadata should contain projectId")
		}
		// Note: ManifestMetadata only has ProjectID, not ProjectName
		// In ArgoCD-aligned model, projects are identified by ID (projectId)
		if !strings.Contains(metadata, "deploymentMode: gitops") {
			t.Error("metadata should contain deploymentMode")
		}
		if !strings.Contains(metadata, "createdBy: user@example.com") {
			t.Error("metadata should contain createdBy")
		}
		if !strings.Contains(metadata, "commitSha: abc123def456") {
			t.Error("metadata should contain commitSha")
		}
		if !strings.Contains(metadata, "repositoryId: repo-789") {
			t.Error("metadata should contain repositoryId")
		}
	})

	t.Run("request without repository", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-456",
			Name:           "test-app",
			Namespace:      "default",
			RGDName:        "test",
			RGDNamespace:   "kro-system",
			DeploymentMode: ModeDirect,
			CreatedBy:      "admin",
			CreatedAt:      now,
		}

		metadata, err := g.GenerateMetadata(req, "")
		if err != nil {
			t.Fatalf("GenerateMetadata() error: %v", err)
		}

		// Should have empty repository ID
		if strings.Contains(metadata, "repositoryId: repo-") {
			t.Error("metadata should not contain non-empty repositoryId when repository is nil")
		}
	})
}

func TestGenerator_GenerateCommitMessage(t *testing.T) {
	g := NewGenerator()
	now := time.Now()

	t.Run("basic message", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-123",
			Name:           "my-app",
			Namespace:      "production",
			RGDName:        "application-stack",
			DeploymentMode: ModeGitOps,
			CreatedBy:      "user@example.com",
			CreatedAt:      now,
		}

		msg := g.GenerateCommitMessage(req)

		// Check subject line
		if !strings.Contains(msg, "Deploy production/my-app (RGD: application-stack)") {
			t.Error("commit message should contain subject line")
		}

		// Check body
		if !strings.Contains(msg, "Instance ID: inst-123") {
			t.Error("commit message should contain instance ID")
		}
		if !strings.Contains(msg, "Created by: user@example.com") {
			t.Error("commit message should contain created by")
		}
		if !strings.Contains(msg, "Deployment mode: gitops") {
			t.Error("commit message should contain deployment mode")
		}

		// Check footer
		if !strings.Contains(msg, "Managed by Knodex GitOps") {
			t.Error("commit message should contain footer")
		}
	})

	t.Run("with project", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-456",
			Name:           "proj-app",
			Namespace:      "default",
			RGDName:        "proj-stack",
			ProjectID:      "acme-proj",
			DeploymentMode: ModeHybrid,
			CreatedBy:      "admin@acme.com",
			CreatedAt:      now,
		}

		msg := g.GenerateCommitMessage(req)

		if !strings.Contains(msg, "Project: acme-proj") {
			t.Error("commit message should contain project when set")
		}
	})

	t.Run("without project", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-789",
			Name:           "simple-app",
			Namespace:      "default",
			RGDName:        "simple",
			DeploymentMode: ModeDirect,
			CreatedBy:      "admin",
			CreatedAt:      now,
		}

		msg := g.GenerateCommitMessage(req)

		if strings.Contains(msg, "Project:") && !strings.Contains(msg, "Project: ") {
			t.Error("commit message should not contain project when not set")
		}
	})
}

func TestGenerator_GenerateManifestPath(t *testing.T) {
	g := NewGenerator()

	t.Run("valid paths", func(t *testing.T) {
		tests := []struct {
			name     string
			req      *DeployRequest
			basePath string
			want     string
		}{
			{
				name:     "default base path",
				req:      &DeployRequest{Namespace: "production", Name: "my-app"},
				basePath: "",
				want:     "instances/production/my-app.yaml",
			},
			{
				name:     "custom base path",
				req:      &DeployRequest{Namespace: "staging", Name: "test-app"},
				basePath: "manifests/kro",
				want:     "manifests/kro/staging/test-app.yaml",
			},
			{
				name:     "default namespace",
				req:      &DeployRequest{Namespace: "default", Name: "nginx"},
				basePath: "k8s",
				want:     "k8s/default/nginx.yaml",
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				got, err := g.GenerateManifestPath(tt.req, tt.basePath)
				if err != nil {
					t.Fatalf("GenerateManifestPath() unexpected error: %v", err)
				}
				if got != tt.want {
					t.Errorf("GenerateManifestPath() = %v, want %v", got, tt.want)
				}
			})
		}
	})

	t.Run("path traversal prevention", func(t *testing.T) {
		// SECURITY: These tests verify that path traversal attacks are blocked
		tests := []struct {
			name      string
			namespace string
			instance  string
		}{
			{"traversal dots in namespace", "../../etc", "passwd"},
			{"traversal dots in name", "default", "../../etc/passwd"},
			{"forward slash in namespace", "default/../../etc", "app"},
			{"forward slash in name", "default", "app/../../../etc/passwd"},
			{"backslash traversal", "..\\..\\windows", "system32"},
			{"null byte attempt", "default", "app\x00malicious"},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				req := &DeployRequest{Namespace: tt.namespace, Name: tt.instance}
				path, err := g.GenerateManifestPath(req, "instances")

				// Should either return an error OR the path should not contain ".."
				if err == nil && strings.Contains(path, "..") {
					t.Errorf("Path traversal not prevented: got path %q", path)
				}
			})
		}
	})

	t.Run("invalid inputs", func(t *testing.T) {
		tests := []struct {
			name      string
			namespace string
			instance  string
		}{
			{"empty namespace", "", "my-app"},
			{"empty name", "default", ""},
			{"uppercase namespace", "Production", "my-app"},
			{"uppercase name", "production", "My-App"},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				req := &DeployRequest{Namespace: tt.namespace, Name: tt.instance}
				_, err := g.GenerateManifestPath(req, "instances")
				if err == nil {
					t.Error("expected error for invalid input")
				}
			})
		}
	})
}

func TestGenerator_GenerateMetadataPath(t *testing.T) {
	g := NewGenerator()

	t.Run("valid paths", func(t *testing.T) {
		tests := []struct {
			name     string
			req      *DeployRequest
			basePath string
			want     string
		}{
			{
				name:     "default base path",
				req:      &DeployRequest{Namespace: "production", Name: "my-app"},
				basePath: "",
				want:     "instances/production/.metadata/my-app.yaml",
			},
			{
				name:     "custom base path",
				req:      &DeployRequest{Namespace: "staging", Name: "test-app"},
				basePath: "manifests/kro",
				want:     "manifests/kro/staging/.metadata/test-app.yaml",
			},
			{
				name:     "default namespace",
				req:      &DeployRequest{Namespace: "default", Name: "nginx"},
				basePath: "k8s",
				want:     "k8s/default/.metadata/nginx.yaml",
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				got, err := g.GenerateMetadataPath(tt.req, tt.basePath)
				if err != nil {
					t.Fatalf("GenerateMetadataPath() unexpected error: %v", err)
				}
				if got != tt.want {
					t.Errorf("GenerateMetadataPath() = %v, want %v", got, tt.want)
				}
			})
		}
	})

	t.Run("path traversal prevention", func(t *testing.T) {
		// SECURITY: These tests verify that path traversal attacks are blocked
		tests := []struct {
			name      string
			namespace string
			instance  string
		}{
			{"traversal dots", "../../etc", "passwd"},
			{"traversal in name", "default", "../../etc/passwd"},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				req := &DeployRequest{Namespace: tt.namespace, Name: tt.instance}
				path, err := g.GenerateMetadataPath(req, "instances")

				// Should either return an error OR the path should not contain ".."
				if err == nil && strings.Contains(path, "..") {
					t.Errorf("Path traversal not prevented: got path %q", path)
				}
			})
		}
	})
}

func TestGenerator_GenerateDeleteCommitMessage(t *testing.T) {
	g := NewGenerator()

	msg := g.GenerateDeleteCommitMessage("production", "my-app", "application-stack", "admin@example.com")

	// Check subject line
	if !strings.Contains(msg, "Delete production/my-app (RGD: application-stack)") {
		t.Error("delete commit message should contain subject line")
	}

	// Check body
	if !strings.Contains(msg, "Deleted by: admin@example.com") {
		t.Error("delete commit message should contain deleted by")
	}
	if !strings.Contains(msg, "Timestamp:") {
		t.Error("delete commit message should contain timestamp")
	}

	// Check footer
	if !strings.Contains(msg, "Managed by Knodex GitOps") {
		t.Error("delete commit message should contain footer")
	}
}

func TestGenerator_GenerateKustomization(t *testing.T) {
	g := NewGenerator()

	t.Run("empty namespace", func(t *testing.T) {
		_, err := g.GenerateKustomization("", []string{"app.yaml"})
		if err == nil {
			t.Error("expected error for empty namespace")
		}
		if !strings.Contains(err.Error(), "namespace is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("valid kustomization", func(t *testing.T) {
		resources := []string{"app.yaml", "service.yaml", "configmap.yaml"}
		kustomization, err := g.GenerateKustomization("production", resources)
		if err != nil {
			t.Fatalf("GenerateKustomization() error: %v", err)
		}

		// Check header
		if !strings.Contains(kustomization, "# Kustomization for Knodex") {
			t.Error("kustomization should contain header comment")
		}

		// Check structure
		if !strings.Contains(kustomization, "apiVersion: kustomize.config.k8s.io/v1beta1") {
			t.Error("kustomization should contain apiVersion")
		}
		if !strings.Contains(kustomization, "kind: Kustomization") {
			t.Error("kustomization should contain kind")
		}
		if !strings.Contains(kustomization, "namespace: production") {
			t.Error("kustomization should contain namespace")
		}

		// Check resources
		if !strings.Contains(kustomization, "app.yaml") {
			t.Error("kustomization should contain app.yaml resource")
		}
		if !strings.Contains(kustomization, "service.yaml") {
			t.Error("kustomization should contain service.yaml resource")
		}
		if !strings.Contains(kustomization, "configmap.yaml") {
			t.Error("kustomization should contain configmap.yaml resource")
		}
	})

	t.Run("empty resources", func(t *testing.T) {
		kustomization, err := g.GenerateKustomization("default", []string{})
		if err != nil {
			t.Fatalf("GenerateKustomization() error: %v", err)
		}

		if !strings.Contains(kustomization, "resources: []") {
			t.Error("kustomization should handle empty resources")
		}
	})
}
