package deployment

import (
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/knodex/knodex/server/internal/k8s/parser"
	"github.com/knodex/knodex/server/internal/util/sanitize"
)

// Generator creates Kubernetes manifests and metadata files
type Generator struct {
	// includeMetadata adds tracking annotations to generated manifests
	includeMetadata bool
}

// NewGenerator creates a new manifest generator
func NewGenerator() *Generator {
	return &Generator{
		includeMetadata: true,
	}
}

// SetIncludeMetadata enables or disables metadata annotations in manifests
func (g *Generator) SetIncludeMetadata(include bool) {
	g.includeMetadata = include
}

// GenerateManifest creates a Kubernetes manifest YAML from a deploy request
func (g *Generator) GenerateManifest(req *DeployRequest) (string, error) {
	if req == nil {
		return "", fmt.Errorf("deploy request cannot be nil")
	}
	if req.Name == "" {
		return "", fmt.Errorf("instance name is required")
	}
	if req.Namespace == "" {
		return "", fmt.Errorf("instance namespace is required")
	}
	if req.APIVersion == "" {
		return "", fmt.Errorf("api version is required")
	}
	if req.Kind == "" {
		return "", fmt.Errorf("kind is required")
	}

	// Build labels
	// Note: KRO automatically sets "kro.run/resource-graph-definition-name" label on instances
	// Note: app.kubernetes.io/managed-by will be set by KRO or GitOps tool (ArgoCD/Flux)
	labels := map[string]interface{}{
		"app.kubernetes.io/name":    req.Name,
		"knodex.io/deployment-mode": string(req.DeploymentMode),
	}
	if req.ProjectID != "" {
		labels["knodex.io/project"] = req.ProjectID
	}

	// Build annotations - all dashboard-specific metadata uses knodex.io prefix
	annotations := map[string]interface{}{
		"knodex.io/instance-id": req.InstanceID,
		"knodex.io/created-by":  req.CreatedBy,
		"knodex.io/created-at":  req.CreatedAt.Format(time.RFC3339),
	}
	if req.ProjectID != "" {
		annotations["knodex.io/project-id"] = req.ProjectID
	}

	// Build the manifest
	manifest := &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": req.APIVersion,
			"kind":       req.Kind,
			"metadata": map[string]interface{}{
				"name":        req.Name,
				"namespace":   req.Namespace,
				"labels":      labels,
				"annotations": annotations,
			},
			"spec": req.Spec,
		},
	}

	// Convert to YAML using parser library
	yamlStr, err := parser.ToYAMLString(manifest.Object)
	if err != nil {
		return "", fmt.Errorf("failed to marshal manifest to YAML: %w", err)
	}

	// Add header comment
	header := fmt.Sprintf("# Generated by Knodex\n# Instance: %s/%s\n# RGD: %s\n# Created: %s\n# DO NOT EDIT - managed by Knodex GitOps\n---\n",
		req.Namespace, req.Name, req.RGDName, req.CreatedAt.Format(time.RFC3339))

	return header + yamlStr, nil
}

// GenerateMetadata creates a metadata YAML file for tracking
func (g *Generator) GenerateMetadata(req *DeployRequest, commitSHA string) (string, error) {
	if req == nil {
		return "", fmt.Errorf("deploy request cannot be nil")
	}

	metadata := ManifestMetadata{
		InstanceID:     req.InstanceID,
		Name:           req.Name,
		Namespace:      req.Namespace,
		RGDName:        req.RGDName,
		RGDNamespace:   req.RGDNamespace,
		ProjectID:      req.ProjectID,
		DeploymentMode: req.DeploymentMode,
		CreatedBy:      req.CreatedBy,
		CreatedAt:      req.CreatedAt,
		CommitSHA:      commitSHA,
	}

	if req.Repository != nil {
		metadata.RepositoryID = req.Repository.ID
	}

	yamlStr, err := parser.ToYAMLString(metadata)
	if err != nil {
		return "", fmt.Errorf("failed to marshal metadata to YAML: %w", err)
	}

	header := "# Knodex Instance Metadata\n# DO NOT EDIT - automatically generated\n---\n"
	return header + yamlStr, nil
}

// GenerateCommitMessage creates a commit message for the manifest
func (g *Generator) GenerateCommitMessage(req *DeployRequest) string {
	var sb strings.Builder

	// Subject line
	sb.WriteString(fmt.Sprintf("Deploy %s/%s (RGD: %s)\n", req.Namespace, req.Name, req.RGDName))

	// Body
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("Instance ID: %s\n", req.InstanceID))
	sb.WriteString(fmt.Sprintf("Created by: %s\n", req.CreatedBy))
	sb.WriteString(fmt.Sprintf("Deployment mode: %s\n", req.DeploymentMode))
	if req.ProjectID != "" {
		sb.WriteString(fmt.Sprintf("Project: %s\n", req.ProjectID))
	}
	sb.WriteString(fmt.Sprintf("Timestamp: %s\n", req.CreatedAt.Format(time.RFC3339)))

	// Footer
	sb.WriteString("\n")
	sb.WriteString("Managed by Knodex GitOps")

	return sb.String()
}

// sanitizePathComponent removes path traversal sequences and validates DNS-1123 format
// SECURITY: Prevents path traversal attacks (CWE-22)
func sanitizePathComponent(component string) (string, error) {
	return sanitize.PathComponent(component)
}

// GenerateManifestPath creates the file path for a manifest in the repository
// SECURITY: Validates inputs to prevent path traversal attacks
func (g *Generator) GenerateManifestPath(req *DeployRequest, basePath string) (string, error) {
	if basePath == "" {
		basePath = "instances"
	}

	// Sanitize namespace and name to prevent path traversal
	namespace, err := sanitizePathComponent(req.Namespace)
	if err != nil {
		return "", fmt.Errorf("invalid namespace: %w", err)
	}

	name, err := sanitizePathComponent(req.Name)
	if err != nil {
		return "", fmt.Errorf("invalid name: %w", err)
	}

	// Build path safely using filepath.Join
	path := filepath.Join(basePath, namespace, name+".yaml")

	// Defense in depth: ensure path stays within basePath
	cleanBasePath := filepath.Clean(basePath)
	cleanPath := filepath.Clean(path)
	if !strings.HasPrefix(cleanPath, cleanBasePath) {
		return "", fmt.Errorf("path traversal detected: path escapes base directory")
	}

	// Convert to forward slashes for Git compatibility (Git uses forward slashes)
	return filepath.ToSlash(path), nil
}

// GenerateMetadataPath creates the file path for metadata in the repository
// SECURITY: Validates inputs to prevent path traversal attacks
func (g *Generator) GenerateMetadataPath(req *DeployRequest, basePath string) (string, error) {
	if basePath == "" {
		basePath = "instances"
	}

	// Sanitize namespace and name to prevent path traversal
	namespace, err := sanitizePathComponent(req.Namespace)
	if err != nil {
		return "", fmt.Errorf("invalid namespace: %w", err)
	}

	name, err := sanitizePathComponent(req.Name)
	if err != nil {
		return "", fmt.Errorf("invalid name: %w", err)
	}

	// Build path safely using filepath.Join
	path := filepath.Join(basePath, namespace, ".metadata", name+".yaml")

	// Defense in depth: ensure path stays within basePath
	cleanBasePath := filepath.Clean(basePath)
	cleanPath := filepath.Clean(path)
	if !strings.HasPrefix(cleanPath, cleanBasePath) {
		return "", fmt.Errorf("path traversal detected: path escapes base directory")
	}

	// Convert to forward slashes for Git compatibility (Git uses forward slashes)
	return filepath.ToSlash(path), nil
}

// GenerateDeleteCommitMessage creates a commit message for deleting a manifest
func (g *Generator) GenerateDeleteCommitMessage(namespace, name, rgdName, deletedBy string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("Delete %s/%s (RGD: %s)\n", namespace, name, rgdName))
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("Deleted by: %s\n", deletedBy))
	sb.WriteString(fmt.Sprintf("Timestamp: %s\n", time.Now().Format(time.RFC3339)))
	sb.WriteString("\n")
	sb.WriteString("Managed by Knodex GitOps")

	return sb.String()
}

// GenerateKustomization creates a kustomization.yaml file for a namespace
func (g *Generator) GenerateKustomization(namespace string, resources []string) (string, error) {
	if namespace == "" {
		return "", fmt.Errorf("namespace is required")
	}

	kustomization := map[string]interface{}{
		"apiVersion": "kustomize.config.k8s.io/v1beta1",
		"kind":       "Kustomization",
		"namespace":  namespace,
		"resources":  resources,
	}

	yamlStr, err := parser.ToYAMLString(kustomization)
	if err != nil {
		return "", fmt.Errorf("failed to marshal kustomization to YAML: %w", err)
	}

	header := "# Kustomization for Knodex managed resources\n# DO NOT EDIT - automatically generated\n---\n"
	return header + yamlStr, nil
}
