// Copyright 2026 Knodex Authors
// SPDX-License-Identifier: AGPL-3.0-only

package deployment

import (
	"fmt"
	"strings"
	"time"

	"github.com/knodex/knodex/server/internal/k8s/parser"
)

// Generator creates Kubernetes manifests
type Generator struct{}

// NewGenerator creates a new manifest generator
func NewGenerator() *Generator {
	return &Generator{}
}

// GenerateManifest creates a Kubernetes manifest YAML from a deploy request
func (g *Generator) GenerateManifest(req *DeployRequest) (string, error) {
	if req == nil {
		return "", fmt.Errorf("deploy request cannot be nil")
	}
	if req.Name == "" {
		return "", fmt.Errorf("instance name is required")
	}
	if !req.IsClusterScoped && req.Namespace == "" {
		return "", fmt.Errorf("instance namespace is required")
	}
	if req.APIVersion == "" {
		return "", fmt.Errorf("api version is required")
	}
	if req.Kind == "" {
		return "", fmt.Errorf("kind is required")
	}

	// Build labels, annotations, and metadata via shared builder
	// Note: KRO automatically sets "kro.run/resource-graph-definition-name" label on instances
	// Note: app.kubernetes.io/managed-by will be set by KRO or GitOps tool (ArgoCD/Flux)
	mb := NewInstanceMetadataBuilder(req)

	// Build the manifest
	manifest := mb.BuildUnstructured(req.APIVersion, req.Kind, req.Spec)

	// Convert to YAML using parser library
	yamlStr, err := parser.ToYAMLString(manifest.Object)
	if err != nil {
		return "", fmt.Errorf("failed to marshal manifest to YAML: %w", err)
	}

	// Add header comment — use scope-appropriate instance identifier
	var instanceRef string
	if req.IsClusterScoped {
		instanceRef = req.Name
	} else {
		instanceRef = req.Namespace + "/" + req.Name
	}
	header := fmt.Sprintf("# Generated by Knodex\n# Instance: %s\n# RGD: %s\n# Created: %s\n# DO NOT EDIT - managed by Knodex GitOps\n---\n",
		instanceRef, req.RGDName, req.CreatedAt.Format(time.RFC3339))

	return header + yamlStr, nil
}

// GenerateCommitMessage creates a commit message for the manifest
func (g *Generator) GenerateCommitMessage(req *DeployRequest) string {
	var sb strings.Builder

	// Subject line — scope-aware instance reference
	if req.IsClusterScoped {
		sb.WriteString(fmt.Sprintf("Deploy %s [cluster-scoped] (RGD: %s)\n", req.Name, req.RGDName))
	} else {
		sb.WriteString(fmt.Sprintf("Deploy %s/%s (RGD: %s)\n", req.Namespace, req.Name, req.RGDName))
	}

	// Body
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("Instance ID: %s\n", req.InstanceID))
	sb.WriteString(fmt.Sprintf("Created by: %s\n", req.CreatedBy))
	sb.WriteString(fmt.Sprintf("Deployment mode: %s\n", req.DeploymentMode))
	if req.IsClusterScoped {
		sb.WriteString("Scope: cluster\n")
	}
	if req.ProjectID != "" {
		sb.WriteString(fmt.Sprintf("Project: %s\n", req.ProjectID))
	}
	sb.WriteString(fmt.Sprintf("Timestamp: %s\n", req.CreatedAt.Format(time.RFC3339)))

	// Footer
	sb.WriteString("\n")
	sb.WriteString("Managed by Knodex GitOps")

	return sb.String()
}

// GenerateManifestPath creates the file path for a manifest in the repository.
// SECURITY: Validates inputs to prevent path traversal attacks (CWE-22)
func (g *Generator) GenerateManifestPath(req *DeployRequest, basePath string) (string, error) {
	return ManifestPathFor(req.Name, req.Namespace, req.Kind, req.IsClusterScoped, basePath)
}

// GenerateDeleteCommitMessage creates a commit message for deleting a manifest.
// Scope-aware: cluster-scoped deletions use name-only format with [cluster-scoped] indicator.
func (g *Generator) GenerateDeleteCommitMessage(namespace, name, rgdName, deletedBy string, isClusterScoped bool) string {
	var sb strings.Builder

	// Subject line — scope-aware instance reference
	if isClusterScoped {
		sb.WriteString(fmt.Sprintf("Delete %s [cluster-scoped] (RGD: %s)\n", name, rgdName))
	} else {
		sb.WriteString(fmt.Sprintf("Delete %s/%s (RGD: %s)\n", namespace, name, rgdName))
	}

	// Body
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("Deleted by: %s\n", deletedBy))
	if isClusterScoped {
		sb.WriteString("Scope: cluster\n")
	}
	sb.WriteString(fmt.Sprintf("Timestamp: %s\n", time.Now().Format(time.RFC3339)))
	sb.WriteString("\n")
	sb.WriteString("Managed by Knodex GitOps")

	return sb.String()
}
