// Copyright 2026 Knodex Authors
// SPDX-License-Identifier: AGPL-3.0-only

package deployment

import (
	"strings"
	"testing"
	"time"
)

func TestNewGenerator(t *testing.T) {
	g := NewGenerator()
	if g == nil {
		t.Fatal("NewGenerator() returned nil")
	}
}

func TestGenerator_GenerateManifest(t *testing.T) {
	g := NewGenerator()
	now := time.Now()

	t.Run("nil request", func(t *testing.T) {
		_, err := g.GenerateManifest(nil)
		if err == nil {
			t.Error("expected error for nil request")
		}
		if !strings.Contains(err.Error(), "cannot be nil") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("empty name", func(t *testing.T) {
		req := &DeployRequest{
			Name:      "",
			Namespace: "default",
		}
		_, err := g.GenerateManifest(req)
		if err == nil {
			t.Error("expected error for empty name")
		}
		if !strings.Contains(err.Error(), "instance name is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("empty namespace", func(t *testing.T) {
		req := &DeployRequest{
			Name:      "test",
			Namespace: "",
		}
		_, err := g.GenerateManifest(req)
		if err == nil {
			t.Error("expected error for empty namespace")
		}
		if !strings.Contains(err.Error(), "instance namespace is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("empty api version", func(t *testing.T) {
		req := &DeployRequest{
			Name:       "test",
			Namespace:  "default",
			APIVersion: "",
			Kind:       "MyResource",
		}
		_, err := g.GenerateManifest(req)
		if err == nil {
			t.Error("expected error for empty api version")
		}
		if !strings.Contains(err.Error(), "api version is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("empty kind", func(t *testing.T) {
		req := &DeployRequest{
			Name:       "test",
			Namespace:  "default",
			APIVersion: "example.com/v1",
			Kind:       "",
		}
		_, err := g.GenerateManifest(req)
		if err == nil {
			t.Error("expected error for empty kind")
		}
		if !strings.Contains(err.Error(), "kind is required") {
			t.Errorf("unexpected error: %v", err)
		}
	})

	t.Run("valid request", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-123",
			Name:           "my-app",
			Namespace:      "production",
			APIVersion:     "kro.run/v1alpha1",
			Kind:           "Application",
			RGDName:        "application-stack",
			RGDNamespace:   "kro-system",
			DeploymentMode: ModeGitOps,
			ProjectID:      "proj-456",
			CreatedBy:      "user@example.com",
			CreatedAt:      now,
			Spec: map[string]interface{}{
				"replicas": 3,
				"image":    "nginx:latest",
			},
		}

		manifest, err := g.GenerateManifest(req)
		if err != nil {
			t.Fatalf("GenerateManifest() error: %v", err)
		}

		// Check header
		if !strings.Contains(manifest, "# Generated by Knodex") {
			t.Error("manifest should contain header comment")
		}
		if !strings.Contains(manifest, "Instance: production/my-app") {
			t.Error("manifest should contain instance info in header")
		}

		// Check basic structure
		if !strings.Contains(manifest, "apiVersion: kro.run/v1alpha1") {
			t.Error("manifest should contain apiVersion")
		}
		if !strings.Contains(manifest, "kind: Application") {
			t.Error("manifest should contain kind")
		}
		if !strings.Contains(manifest, "name: my-app") {
			t.Error("manifest should contain name")
		}
		if !strings.Contains(manifest, "namespace: production") {
			t.Error("manifest should contain namespace")
		}

		// Check labels
		if !strings.Contains(manifest, "app.kubernetes.io/name: my-app") {
			t.Error("manifest should contain app.kubernetes.io/name label")
		}
		// Note: KRO automatically sets kro.run/resource-graph-definition-name label
		// Note: app.kubernetes.io/managed-by is set by KRO or GitOps tool (ArgoCD/Flux)
		if !strings.Contains(manifest, "knodex.io/deployment-mode: gitops") {
			t.Error("manifest should contain deployment-mode label")
		}
		if !strings.Contains(manifest, "knodex.io/project: proj-456") {
			t.Error("manifest should contain project label")
		}

		// Check annotations - all dashboard-specific metadata uses knodex.io prefix
		if !strings.Contains(manifest, "knodex.io/instance-id: inst-123") {
			t.Error("manifest should contain instance-id annotation")
		}
		if !strings.Contains(manifest, "knodex.io/created-by: user@example.com") {
			t.Error("manifest should contain created-by annotation")
		}
		if !strings.Contains(manifest, "knodex.io/project-id: proj-456") {
			t.Error("manifest should contain project-id annotation")
		}

		// Check spec
		if !strings.Contains(manifest, "replicas: 3") {
			t.Error("manifest should contain spec replicas")
		}
		if !strings.Contains(manifest, "image: nginx:latest") {
			t.Error("manifest should contain spec image")
		}
	})

	t.Run("request without project", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-789",
			Name:           "simple-app",
			Namespace:      "default",
			APIVersion:     "kro.run/v1alpha1",
			Kind:           "Application",
			RGDName:        "simple",
			RGDNamespace:   "kro-system",
			DeploymentMode: ModeDirect,
			CreatedBy:      "admin",
			CreatedAt:      now,
			Spec:           map[string]interface{}{},
		}

		manifest, err := g.GenerateManifest(req)
		if err != nil {
			t.Fatalf("GenerateManifest() error: %v", err)
		}

		// Should not contain project fields
		if strings.Contains(manifest, "knodex.io/project:") {
			t.Error("manifest should not contain project label when not set")
		}
		if strings.Contains(manifest, "knodex.io/project-id:") {
			t.Error("manifest should not contain project-id annotation when not set")
		}
	})
}

func TestGenerator_GenerateCommitMessage(t *testing.T) {
	g := NewGenerator()
	now := time.Now()

	t.Run("basic message", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-123",
			Name:           "my-app",
			Namespace:      "production",
			RGDName:        "application-stack",
			DeploymentMode: ModeGitOps,
			CreatedBy:      "user@example.com",
			CreatedAt:      now,
		}

		msg := g.GenerateCommitMessage(req)

		// Check subject line
		if !strings.Contains(msg, "Deploy production/my-app (RGD: application-stack)") {
			t.Error("commit message should contain subject line")
		}

		// Check body
		if !strings.Contains(msg, "Instance ID: inst-123") {
			t.Error("commit message should contain instance ID")
		}
		if !strings.Contains(msg, "Created by: user@example.com") {
			t.Error("commit message should contain created by")
		}
		if !strings.Contains(msg, "Deployment mode: gitops") {
			t.Error("commit message should contain deployment mode")
		}

		// Check footer
		if !strings.Contains(msg, "Managed by Knodex GitOps") {
			t.Error("commit message should contain footer")
		}
	})

	t.Run("with project", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-456",
			Name:           "proj-app",
			Namespace:      "default",
			RGDName:        "proj-stack",
			ProjectID:      "acme-proj",
			DeploymentMode: ModeHybrid,
			CreatedBy:      "admin@acme.com",
			CreatedAt:      now,
		}

		msg := g.GenerateCommitMessage(req)

		if !strings.Contains(msg, "Project: acme-proj") {
			t.Error("commit message should contain project when set")
		}
	})

	t.Run("without project", func(t *testing.T) {
		req := &DeployRequest{
			InstanceID:     "inst-789",
			Name:           "simple-app",
			Namespace:      "default",
			RGDName:        "simple",
			DeploymentMode: ModeDirect,
			CreatedBy:      "admin",
			CreatedAt:      now,
		}

		msg := g.GenerateCommitMessage(req)

		if strings.Contains(msg, "Project:") && !strings.Contains(msg, "Project: ") {
			t.Error("commit message should not contain project when not set")
		}
	})
}

func TestGenerator_GenerateManifestPath(t *testing.T) {
	g := NewGenerator()

	t.Run("valid paths", func(t *testing.T) {
		tests := []struct {
			name     string
			req      *DeployRequest
			basePath string
			want     string
		}{
			{
				name:     "default base path",
				req:      &DeployRequest{Namespace: "production", Name: "my-app", Kind: "WebApp"},
				basePath: "",
				want:     "instances/production/WebApp/my-app.yaml",
			},
			{
				name:     "custom base path",
				req:      &DeployRequest{Namespace: "staging", Name: "test-app", Kind: "Application"},
				basePath: "manifests/kro",
				want:     "manifests/kro/staging/Application/test-app.yaml",
			},
			{
				name:     "default namespace",
				req:      &DeployRequest{Namespace: "default", Name: "nginx", Kind: "WebServer"},
				basePath: "k8s",
				want:     "k8s/default/WebServer/nginx.yaml",
			},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				got, err := g.GenerateManifestPath(tt.req, tt.basePath)
				if err != nil {
					t.Fatalf("GenerateManifestPath() unexpected error: %v", err)
				}
				if got != tt.want {
					t.Errorf("GenerateManifestPath() = %v, want %v", got, tt.want)
				}
			})
		}
	})

	t.Run("path traversal prevention", func(t *testing.T) {
		// SECURITY: These tests verify that path traversal attacks are blocked
		tests := []struct {
			name      string
			namespace string
			instance  string
		}{
			{"traversal dots in namespace", "../../etc", "passwd"},
			{"traversal dots in name", "default", "../../etc/passwd"},
			{"forward slash in namespace", "default/../../etc", "app"},
			{"forward slash in name", "default", "app/../../../etc/passwd"},
			{"backslash traversal", "..\\..\\windows", "system32"},
			{"null byte attempt", "default", "app\x00malicious"},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				req := &DeployRequest{Namespace: tt.namespace, Name: tt.instance, Kind: "WebApp"}
				path, err := g.GenerateManifestPath(req, "instances")

				// Should either return an error OR the path should not contain ".."
				if err == nil && strings.Contains(path, "..") {
					t.Errorf("Path traversal not prevented: got path %q", path)
				}
			})
		}
	})

	t.Run("invalid inputs", func(t *testing.T) {
		tests := []struct {
			name      string
			namespace string
			kind      string
			instance  string
		}{
			{"empty namespace", "", "WebApp", "my-app"},
			{"empty name", "default", "WebApp", ""},
			{"empty kind", "default", "", "my-app"},
		}

		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				req := &DeployRequest{Namespace: tt.namespace, Name: tt.instance, Kind: tt.kind}
				_, err := g.GenerateManifestPath(req, "instances")
				if err == nil {
					t.Error("expected error for invalid input")
				}
			})
		}
	})
}

func TestGenerator_GenerateDeleteCommitMessage(t *testing.T) {
	g := NewGenerator()

	t.Run("namespace-scoped delete", func(t *testing.T) {
		msg := g.GenerateDeleteCommitMessage("production", "my-app", "application-stack", "admin@example.com", false)

		if !strings.Contains(msg, "Delete production/my-app (RGD: application-stack)") {
			t.Error("delete commit message should contain namespace/name subject line")
		}
		if !strings.Contains(msg, "Deleted by: admin@example.com") {
			t.Error("delete commit message should contain deleted by")
		}
		if !strings.Contains(msg, "Timestamp:") {
			t.Error("delete commit message should contain timestamp")
		}
		if !strings.Contains(msg, "Managed by Knodex GitOps") {
			t.Error("delete commit message should contain footer")
		}
		if strings.Contains(msg, "[cluster-scoped]") {
			t.Error("namespace-scoped delete should NOT contain [cluster-scoped]")
		}
	})

	t.Run("cluster-scoped delete", func(t *testing.T) {
		msg := g.GenerateDeleteCommitMessage("", "global-config", "cluster-rgd", "admin@example.com", true)

		if !strings.Contains(msg, "Delete global-config [cluster-scoped] (RGD: cluster-rgd)") {
			t.Errorf("cluster-scoped delete should use name-only format, got: %s", msg)
		}
		if !strings.Contains(msg, "Scope: cluster") {
			t.Error("cluster-scoped delete should include Scope: cluster")
		}
		if strings.Contains(msg, "/global-config") {
			t.Error("cluster-scoped delete should NOT use namespace/name format")
		}
		if !strings.Contains(msg, "Deleted by: admin@example.com") {
			t.Error("delete commit message should contain deleted by")
		}
	})
}

// --- Cluster-Scoped Tests (STORY-302) ---

func TestGenerator_GenerateManifest_ClusterScoped(t *testing.T) {
	g := NewGenerator()
	now := time.Now()

	t.Run("cluster-scoped omits namespace from manifest", func(t *testing.T) {
		req := &DeployRequest{
			Name:            "my-cluster-config",
			Namespace:       "", // empty for cluster-scoped
			IsClusterScoped: true,
			APIVersion:      "kro.run/v1alpha1",
			Kind:            "ClusterConfig",
			Spec:            map[string]interface{}{"tier": "gold"},
			DeploymentMode:  ModeDirect,
			InstanceID:      "inst-123",
			CreatedBy:       "admin@test.local",
			CreatedAt:       now,
			ProjectID:       "platform",
		}

		yaml, err := g.GenerateManifest(req)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if strings.Contains(yaml, "namespace:") {
			t.Error("cluster-scoped manifest must not contain namespace field")
		}
		if !strings.Contains(yaml, "name: my-cluster-config") {
			t.Error("manifest should contain the instance name")
		}
		if !strings.Contains(yaml, "knodex.io/project: platform") {
			t.Error("manifest should contain project label")
		}
		if !strings.Contains(yaml, "knodex.io/instance-id: inst-123") {
			t.Error("manifest should contain instance-id annotation")
		}
	})

	t.Run("namespace-scoped still includes namespace", func(t *testing.T) {
		req := &DeployRequest{
			Name:            "my-app",
			Namespace:       "production",
			IsClusterScoped: false,
			APIVersion:      "kro.run/v1alpha1",
			Kind:            "Application",
			Spec:            map[string]interface{}{"replicas": int64(1)},
			DeploymentMode:  ModeDirect,
			InstanceID:      "inst-456",
			CreatedBy:       "dev@test.local",
			CreatedAt:       now,
		}

		yaml, err := g.GenerateManifest(req)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !strings.Contains(yaml, "namespace: production") {
			t.Error("namespace-scoped manifest must contain namespace field")
		}
	})

	t.Run("cluster-scoped with empty namespace does not error", func(t *testing.T) {
		req := &DeployRequest{
			Name:            "global-policy",
			Namespace:       "",
			IsClusterScoped: true,
			APIVersion:      "kro.run/v1alpha1",
			Kind:            "ClusterPolicy",
			Spec:            map[string]interface{}{"enforce": true},
			DeploymentMode:  ModeDirect,
			InstanceID:      "inst-789",
			CreatedBy:       "admin@test.local",
			CreatedAt:       now,
		}

		_, err := g.GenerateManifest(req)
		if err != nil {
			t.Fatalf("cluster-scoped with empty namespace should not error: %v", err)
		}
	})
}

func TestGenerator_GenerateManifestPath_ClusterScoped(t *testing.T) {
	g := NewGenerator()

	t.Run("cluster-scoped uses kind-based path", func(t *testing.T) {
		req := &DeployRequest{
			Name:            "my-config",
			IsClusterScoped: true,
			Kind:            "ClusterConfig",
		}
		path, err := g.GenerateManifestPath(req, "instances")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := "instances/cluster-scoped/clusterconfig/my-config.yaml"
		if path != want {
			t.Errorf("got %q, want %q", path, want)
		}
	})

	t.Run("cluster-scoped with custom base path", func(t *testing.T) {
		req := &DeployRequest{
			Name:            "global-policy",
			IsClusterScoped: true,
			Kind:            "Policy",
		}
		path, err := g.GenerateManifestPath(req, "manifests")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := "manifests/cluster-scoped/policy/global-policy.yaml"
		if path != want {
			t.Errorf("got %q, want %q", path, want)
		}
	})

	t.Run("namespace-scoped includes kind", func(t *testing.T) {
		req := &DeployRequest{
			Name:            "my-app",
			Namespace:       "production",
			Kind:            "Application",
			IsClusterScoped: false,
		}
		path, err := g.GenerateManifestPath(req, "instances")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := "instances/production/Application/my-app.yaml"
		if path != want {
			t.Errorf("got %q, want %q", path, want)
		}
	})
}

func TestGenerator_GenerateCommitMessage_ClusterScoped(t *testing.T) {
	g := NewGenerator()
	now := time.Now()

	t.Run("cluster-scoped includes scope indicator", func(t *testing.T) {
		req := &DeployRequest{
			Name:            "global-config",
			IsClusterScoped: true,
			RGDName:         "cluster-config-rgd",
			InstanceID:      "inst-100",
			CreatedBy:       "admin@test.local",
			DeploymentMode:  ModeGitOps,
			CreatedAt:       now,
		}
		msg := g.GenerateCommitMessage(req)
		if !strings.Contains(msg, "[cluster-scoped]") {
			t.Error("commit message should include [cluster-scoped] indicator")
		}
		if !strings.Contains(msg, "Scope: cluster") {
			t.Error("commit message body should include scope")
		}
		if strings.Contains(msg, "/global-config") {
			t.Error("commit message should NOT use namespace/name format for cluster-scoped")
		}
	})

	t.Run("namespace-scoped uses namespace/name format", func(t *testing.T) {
		req := &DeployRequest{
			Name:            "my-app",
			Namespace:       "production",
			IsClusterScoped: false,
			RGDName:         "app-rgd",
			InstanceID:      "inst-200",
			CreatedBy:       "dev@test.local",
			DeploymentMode:  ModeGitOps,
			CreatedAt:       now,
		}
		msg := g.GenerateCommitMessage(req)
		if !strings.Contains(msg, "production/my-app") {
			t.Error("commit message should use namespace/name format")
		}
		if strings.Contains(msg, "[cluster-scoped]") {
			t.Error("commit message should NOT include [cluster-scoped] for namespace-scoped")
		}
	})
}

// TestDeployRequest_GetEffectiveBranch verifies that GetEffectiveBranch respects
// the GitBranch override over the repository default — ensuring pushToGit uses
// the correct branch when a per-deployment override is set.
func TestDeployRequest_GetEffectiveBranch(t *testing.T) {
	tests := []struct {
		name     string
		req      DeployRequest
		expected string
	}{
		{
			name: "GitBranch override wins",
			req: DeployRequest{
				GitBranch:  "feature/deploy-override",
				Repository: &RepositoryConfig{Branch: "main"},
			},
			expected: "feature/deploy-override",
		},
		{
			name: "falls back to repository branch",
			req: DeployRequest{
				GitBranch:  "",
				Repository: &RepositoryConfig{Branch: "develop"},
			},
			expected: "develop",
		},
		{
			name: "falls back to main when nothing set",
			req: DeployRequest{
				GitBranch:  "",
				Repository: &RepositoryConfig{},
			},
			expected: "main",
		},
		{
			name:     "falls back to main when no repo",
			req:      DeployRequest{GitBranch: ""},
			expected: "main",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.req.GetEffectiveBranch()
			if got != tt.expected {
				t.Errorf("GetEffectiveBranch() = %q, want %q", got, tt.expected)
			}
		})
	}
}
